name: deploy

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        # https://github.com/actions/setup-go
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.x
      -
        name: Setup
        run: make setup
      -
        name: Build
        run: make ci
